[tool.poetry]
name = "project-one"
version = "0.1.0"
description = ""
authors = ["Conor-OD"]

[tool.poetry.dependencies]
python = "^3.7"
logger = {path = "../../libs/logger"}
lib-one = {path = "../../libs/lib-one"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
